import {
  SignInButton,
  SignOutButton,
  UserButton,
  useAuth,
} from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const { isSignedIn } = useAuth();

  return (
    <>
      <Head>
        <title>🌕眠</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 flex flex-col items-center min-h-screen text-neutral-200">
        <div className="py-4 w-full flex justify-between items-center">
          🌕 眠
          {isSignedIn ? (
            <UserButton afterSignOutUrl="/" />
          ) : (
            <SignInButton afterSignInUrl="/" />
          )}
        </div>
        <div className="min-h-full py-2 px-4 w-full md:w-1/2 bg-neutral-800 rounded-md">
          Hello
        </div>
      </main>
    </>
  );
}
